package ua.lviv.lgs.domain;

public enum FacultyNames {

	ECONOMIC, FOREIGN_LANGUAGES, PEDAGOGY, PHILOSOPHY, COMPUTER_SCIENCES, MATH, TOURISM, PHILOLOGY, PHYSIC, HISTORY,
	NATURAL_SCIENCES, SPORTS;
}
