package ua.lviv.lgs.domain;

public enum Subjects {
	
	MATHEMATIC, ENGLISH, DEUTSCH, UKRAINIAN_LANGUAGE, HISTORY, PHYSIC, GEOGRAPHY, FOREIGN_LITERATURE, INFORMATIC, BIOLOGY, CHEMISTRY, SPORTS, CERTIFICATE_MARK;
}
